# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 739c7753a2b1db8520bcc940d5ae80fe52a8c8b7460fef7f155cd3799269f67bdaf2de49b1e56b32fc0d04c553e7fde6191bce7dfa2923d1b86e77a1b32b118c

test:
  secret_key_base: b70d42e060979096bcf53336af5fbc651f069979acec3e955ed03ce30b45b768ce033982c6448ce2347f019e1890e6580fad0bc1a09f919bfdc6329a1c4f9ca1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
